### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by leo9223** [furore-fhir/spark#109]
Hello, Everyone.

1. I would like to suggest and request to all dev team. Please implement repository pattern so that user can plug a database of his/her own choice.

2. Please port this to ASP.NET Core as this is a more modern and better way from Microsoft for developing web applications.

**Comment by nzcoward** [comment]
Heya @cknaap is the new version in a branch of this repo? Would be keen to get my hands on it and contribute.

Jono

**Comment by cknaap** [comment]
Thanks for the offer. I'm sorry to disappoint you, but the new version is not on Github.

**Comment by nzcoward** [comment]
Planning to make it a commercial product instead, or just not ready for github?

**Comment by leo9223** [comment]
When the new version will be on the github?

**Comment by cknaap** [comment]
We gave the new version also a new name: Vonk.
It will be a commercial product and thus not on Github.
We will  provide free versions for specific use cases in the near future though.

**Comment by leo9223** [comment]
can you please describe what specific use cases for example?

**Comment by cknaap** [comment]
I'm sorry, but we haven't decided on the terms for free usage. I'll keep you posted when we do.

**Comment by leo9223** [comment]
can you please tell us when you people are releasing Vonk?

**Comment by wahmedswl** [comment]
will this project be maintained or future work will be focused on ```Vonk```?

Thanks

**Comment by cknaap** [comment]
@leo9223 : By now: yes we can, we released it last Thursday. See [the Vonk productpage](http://fhir.furore.com/vonk)

@wahmedswl : On that same page is also our policy for Spark:

This is up to the community. Furore has put a lot of effort in Spark and provides all of this effort to the community. It’s open source, available on GitHub. But Furore will neither port Spark to STU3 nor provide support for DSTU2.

Regards,
