### ISSUE TITLE
Using gzip compression does not work

### ISSUE THREAD

**Issue by ewoutkramer** [furore-fhir/spark#11]
Finally got around to testing compressed request to FHIR server.  Sorry Grahame, but it appears both your and Ewout's servers fail.  It looks like both server are feeding the compressed content directly into XML processing without first decompressing the request content.

[14-6-2014 00:34:45] Richard Schneider: 

PUT http://fhir.healthintersections.com.au/open/Profile/patient?_ignoreVersion=true HTTP/1.1
Category: http://hl7.fhir/example; label="FHIR example"; scheme="http://hl7.org/fhir/tag"
User-Agent: orchestral-client/0.80
Accept: application/atom+xml; q=1.0, application/xml+fhir; q=0.9, application/json+fhir; q=0.8, */*; q=0.1
Content-Type: application/xml+fhir; charset=utf-8
Content-Encoding: gzip
Host: fhir.healthintersections.com.au
Content-Length: 6709
Accept-Encoding: gzip, deflate
Connection: Keep-Alive

**Comment by mharthoorn** [comment]
Richard Schneider still has a pull request for this.

**Comment by cknaap** [comment]
Fixed by [this commit] (https://github.com/furore-fhir/spark/commit/b85e6f37fe0daf85af678b2c72304c2c687c9e0e)
