### ISSUE TITLE
FhirModel.cs issue in STU3 - pre

### ISSUE THREAD

**Issue by HowardEdidin** [furore-fhir/spark#114]
After removing DSTU2 and adding STU3, I was able to resolve most issues except for FhirModel.cs 

```
public IEnumerable<SearchParameter> FindSearchParameters(string resourceName) 
{ 
return SearchParameters.Where(sp => Equals(sp.Base, GetResourceTypeForResourceName(resourceName)) || sp.Base == ResourceType.Resource); 
} 

```
If I remove this, will I break anything?
sp.Base == ResourceType.Resource

**Comment by cknaap** [comment]
It won't find the generic search parameters like _id and lastupdated anymore, since they are defined on Resource.
