### ISSUE TITLE
Signal R exception

### ISSUE THREAD

**Issue by HowardEdidin** [furore-fhir/spark#118]
Exception	Exception caught: 'Microsoft.Practices.Unity.ResolutionFailedException' in Spark.dll ("Resolution of the dependency failed, type = "Microsoft.AspNet.SignalR.Infrastructure.IPerformanceCounterManager", name = "(none)".
Exception occurred while: while resolving.
Exception is: InvalidOperationException - The current type, Microsoft.AspNet.SignalR.Infrastructure.IPerformanceCounterManager, is an interface and cannot be constructed. Are you missing a type mapping?

**Comment by cknaap** [comment]
I don't recall seeing this exception ever in our own Spark instance. Any chance it is a result of your modifications?
