### ISSUE TITLE
Unit Tests Failures

### ISSUE THREAD

**Issue by TonyAbell** [furore-fhir/spark#17]
80: Failed
22: Pass

Are all the unit tests up to date and in working order. 

I am planning on refactoring the project to make it easier to plug in different storage and index providers.
 
Should I make sure the tests are up to date, or are they not being maintained.

**Comment by mharthoorn** [comment]
We have separated

**Comment by mharthoorn** [comment]
We are in the process of readding a new set of unit tests. The previous project is out of date. Also, our primary tool for testing is Sprinkler (http://github.com/furore-fhir/sprinkler)
