### ISSUE TITLE
Spark.Engine nuget-package

### ISSUE THREAD

**Issue by lisney** [furore-fhir/spark#28]
Hi guys!
I am developing FHIR- server using FHIRbase. I suggest you create nuget-package from the assembly "Spark.Engine".

**Comment by mharthoorn** [comment]
Spark.Engine is now available as nuget package.
https://www.nuget.org/packages/Spark.Engine/0.90.2-beta2
Spark.Mongo is the Mongo implementation of Spark:
https://www.nuget.org/packages/Spark.Mongo/0.90.2-beta2
