### ISSUE TITLE
Posting to New Patient #Error 415

### ISSUE THREAD

**Issue by kkatsoulas** [furore-fhir/spark#29]
I try to post:
http://localhost:1396/fhir/Patient/?_format=json

I get the error message:
{
  "resourceType": "OperationOutcome",
  "issue": [
    {
      "severity": "error",
      "details": "StatusCode: 415, ReasonPhrase: 'Unsupported Media Type', Version: 1.1, Content: System.Net.Http.ObjectContent`1[[System.Web.Http.HttpError, System.Web.Http, Version=5.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Headers:\r\n{\r\n  Content-Type: application/json; charset=utf-8\r\n}"
    }
  ]
}

A simple JSON Fhir Message I use is:
{
  "resourceType": "Patient",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Everywoman, Eve. SSN:\r\n            444222222\r\n        \r\n                    \r\n        \r\n        </div>"
  },
  "identifier": [
    {
      "label": "SSN",
      "system": "sid/us-ssn",
      "value": "444222222"
    }
  ],
  "name": [
    {
      "use": "official",
      "family": [
        "Everywoman"
      ],
      "given": [
        "Eve"
      ]
    },
    {
      "family": [
        "Kramer"
      ],
      "given": [
        "Ewout"
      ]
    },
    {
      "family": [
        "Kramer"
      ],
      "given": [
        "Ewout"
      ]
    },
    {
      "family": [
        "Kramer"
      ],
      "given": [
        "Ewout"
      ]
    },
    {
      "family": [
        "Kramer"
      ],
      "given": [
        "Ewout"
      ]
    },
    {
      "family": [
        "Kramer"
      ],
      "given": [
        "Ewout"
      ]
    },
    {
      "family": [
        "Kramer"
      ],
      "given": [
        "Ewout"
      ]
    },
    {
      "family": [
        "Kramer"
      ],
      "given": [
        "Ewout"
      ]
    }
  ],
  "telecom": [
    {
      "system": "phone",
      "value": "555-555-2003",
      "use": "work"
    }
  ],
  "gender": {
    "coding": [
      {
        "system": "v3/AdministrativeGender",
        "code": "F"
      }
    ]
  },
  "birthDate": "1976-05-31",
  "address": [
    {
      "use": "home",
      "line": [
        "3333 Home Street"
      ]
    }
  ],
  "managingOrganization": {
    "reference": "Organization/hl7"
  },
  "active": true
}

**Comment by mbaltus** [comment]
When posting a resource, make sure you supply the HTTP headers with a Content-Type.
The ?_format=json just tells the server you expect the response in JSON format, not that the content you are sending is in JSON.
