### ISSUE TITLE
Recognise search parameters with underscore

### ISSUE THREAD

**Issue by mharthoorn** [furore-fhir/spark#32]
AppointmentResponse.ParticipantStatus ends with “_” to avoid overlapping names. The search index algorithm misses this.

**Comment by lenisha** [comment]
Martijn , which branch contains DSTU2 code that is active?

**Comment by mharthoorn** [comment]
Ienisha, the "develop" branch has the latest DSTU2 code.

**Comment by mbaltus** [comment]
This duplicates issue #30
