### ISSUE TITLE
Search-index and database out of sync?

### ISSUE THREAD

**Issue by ewoutkramer** [furore-fhir/spark#37]
$ curl get http://localhost:1496/fhir/Encounter/spark1/_history/spark1        Works! 

$ curl get http://localhost:1496/fhir/Encounter/spark1    does Not work   :(

See https://dl.dropboxusercontent.com/u/7449873/spark-db-issue-3m.zip for a database where this happens

**Comment by mbaltus** [comment]
Probably occurred due to a bug with transactions. Resolved in current version.
