### ISSUE TITLE
Inconsistent version labels in Conformance

### ISSUE THREAD

**Issue by ewoutkramer** [furore-fhir/spark#40]
Question about Conformance - http://spark-dstu2.furore.com/fhir/Conformance lists the FHIR version as 0.2 in the first section, and then 0.4.0 in the other sections (which indicate a published date of April 2, 2015 -- 0.5.0)...  Is this just a management oversight?  :)

**Comment by mbaltus** [comment]
Seems to be fixed in latest Spark version.
