### ISSUE TITLE
ASP.Net 5 / Dependency Injection?

### ISSUE THREAD

**Issue by wilsondy** [furore-fhir/spark#46]
I'm writing a Couchbase Store for Spark and was wondering when you foresee adding Dependency Injection?  I see a comment in FhirController that suggests it is planned.

**Comment by mharthoorn** [comment]
We are currently implementing DI using Unity. We plan to take a second look at it when we move SPARK to ASP.NET 5 (vNext) which will happen somewhere in 2016 (after RTM).

**Comment by aceptra** [comment]
Dylan,

We are looking at using Spark, but would rather Couchbase as the store. Did you get anywhere with this?
