### ISSUE TITLE
Need some help on Crucible for FHIR Tests

### ISSUE THREAD

**Issue by revathysreenath** [furore-fhir/spark#47]
Hi All,

I am trying to use Crucible to determine the compliance to FHIR specifications by executing the predefined FHIR Tests.When i try to run the tests , it is executing indefinitely. Can anyone please help me with this.  I am unable to find good documentation on using this tool. 

Also can anyone please help me with following information :
1. Should the FHIR server which I am using be a public server to run these tests?
2. Is it possible for me to download the tests and tool and run it locally?
3. Is supporting software conformance resource mandatory for the tool to be used?

Thanks,
Revathy

**Comment by jawalonoski** [comment]
Hi Revathy, please see my response here: https://github.com/fhir-crucible/fhir_dstu2/issues/1
