### ISSUE TITLE
Search Criteria not working

### ISSUE THREAD

**Issue by shraddha30** [furore-fhir/spark#50]
Till Wednesday night, a search like

http://spark.furore.com/fhir/DiagnosticReport?subject:Patient.family=Bor

provided results.

This doesn't seem to be working now, even though when I go to http://spark.furore.com/fhir/DiagnosticReport I see results that have the patient's family name as Bor.

**Comment by mbaltus** [comment]
The Spark server has been updated to FHIR version 1.0.1. This server update has caused the search problems and we are working hard to fix them.

**Comment by mbaltus** [comment]
This issue duplicates issue #6.
