### ISSUE TITLE
Build Error in VS

### ISSUE THREAD

**Issue by cunninghamb505** [furore-fhir/spark#51]
Hi All, Went to download the latest build ,and tried to compile but ran into some small errors. I do have a fix if you need. The issue was in the web.config. I had to change the langversion to 5 from 6. May be just something on my end , but in-case someone had the same issue here is the fix.

Error was in webpage 
[No relevant source lines]

in webconfig line below
compilerOptions="/langversion:5
Thanks
Brandon

**Comment by mbaltus** [comment]
Thank you for your comment. We are developing in VS 2015, and although we are trying to keep the C# 6 features out of the code as much as possible, this might have caused your build errors.
