### ISSUE TITLE
Deleted resources show up in search results

### ISSUE THREAD

**Issue by mbaltus** [furore-fhir/spark#54]
Retrieving a single deleted resource gives the expected 410 result, but in a search  deleted resources are included in the result bundle.

For example:
DELETE http://spark.furore.com/fhir/Patient/pat4
GET http://spark.furore.com/fhir/Patient/pat4    (results in 410)
GET http://spark.furore.com/fhir/Patient/           (still lists pat4)

**Comment by CorinaCiocanea** [comment]
Fixed on dstu2/develop with commit #cc53b47db7c349c9675adb1fa75184b576670b85
