### ISSUE TITLE
SPARK not honouring _summary=true

### ISSUE THREAD

**Issue by cdaapi** [furore-fhir/spark#55]
When executing http://spark-dstu2.furore.com/fhir/ValueSet?_summary=true

The returned bundle contains values that are not marked as summary.

Executing the same query on Grahame's server only returns a bundle of summary valuesets

**Comment by brianpos** [comment]
This is by the Dotnet client having the summary bjts wrong in the serializes.
It has been fixed in the t4 template version of the client that is in progress.
Have been testing it in our server too.
