### ISSUE TITLE
Initialize new MongoDB store with example-data using MaintenanceController

### ISSUE THREAD

**Issue by magohl** [furore-fhir/spark#56]
Hi,

Just started looking at the fhir-spark application (DSTU2-master) and want to initialize an empty mongodb instance with sample-data.

The MaintenanceController/Initialize action, where i thought the MaintenanceService/Initalize() method would be kicked off, is empty. I am surely just missing where and how this is supposed to be done. Anybody who can point me in the right direction?

**Comment by mbaltus** [comment]
All the logic is in Hubs/InitializerHub.cs. If you call [base]/Maintenance/Initialize, a connection with the InitializeHub websocket is made.
