### ISSUE TITLE
Searching resources by id fails

### ISSUE THREAD

**Issue by ewoutkramer** [furore-fhir/spark#6]
When doing this:
`http://spark.furore.com/fhir/DiagnosticReport?subject:Patient=pat2`
the search will return *all* DiagnosticReports

However, when doing this:
`http://spark.furore.com/fhir/DiagnosticReport?subject:Patient._id=pat2`
search works correctly. 

Search is also correct when doing this:
`http://spark.furore.com/fhir/DiagnosticReport?subject=Patient/pat2`

**Comment by michelemottini** [comment]
Also:

````
http://spark.furore.com/fhir/Observation?subject=Patient/f001
````

returns some observations, but 

````
http://spark.furore.com/fhir/Observation?subject=http://spark.furore.com/fhir/Patient/f001
````

returns no results - but according to the [specs](http://www.hl7.org/implement/standards/fhir/search.html#reference) it is equivalent to the first search.

**Comment by mbaltus** [comment]
All of the examples above now return no results.
