### ISSUE TITLE
Problem searching for effective in Observation

### ISSUE THREAD

**Issue by jokkis0** [furore-fhir/spark#61]
Hi, 
I trying to search for a observation by effective (DateTime). 
I have tried this:
http://spark.furore.com/fhir/Observation?subject.identifier=12345&effectiveDateTime=2012-09-17
This does not give me any result. 
Could you please help me how the best way is to search for effective(period og dateTime)?

Thanks

**Comment by mbaltus** [comment]
For me, Spark returns 16 resources on this search. All of these are observations where the identifier of the subject is 12345.
effectiveDateTime is not a valid search parameter, and Spark will ignore that, so I guess the result Spark sends is not what you were looking for. For valid search parameters, check the list on the bottom of the resource page. For the effective date on Observation, you need to use 'date':  Obtained date/time. If the obtained element is a period, a date that falls in the period	Observation.effective[x]

So your search would be:
http://spark.furore.com/fhir/Observation?subject.identifier=12345&date=2012-09-17
