### ISSUE TITLE
Delete in transaction gives error

### ISSUE THREAD

**Issue by mbaltus** [furore-fhir/spark#66]
When deleting a resource through a transaction bundle the resource is deleted, but Spark returns a 500 error:

`<OperationOutcome xmlns="http://hl7.org/fhir">
	<issue>
		<severity value="error" />
		<diagnostics value="Exception: This key is not valid for storage: Patient/spark981" />
	</issue>
	<issue>
		<severity value="information" />
		<diagnostics value="   at Spark.Store.Mongo.SparkBsonHelper.AssertKeyIsValid(IKey key)&#xD;&#xA;   at Spark.Store.Mongo.SparkBsonHelper.AddMetaData(BsonDocument document, IKey key)&#xD;&#xA;   at Spark.Store.Mongo.SparkBsonHelper.ToBsonDocument(Interaction entry)&#xD;&#xA;   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()&#xD;&#xA;   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)&#xD;&#xA;   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)&#xD;&#xA;   at Spark.Store.Mongo.MongoFhirStore.Add(IEnumerable`1 interactions)&#xD;&#xA;   at Spark.Service.FhirService.Transaction(Bundle bundle)&#xD;&#xA;   at lambda_method(Closure , Object , Object[] )&#xD;&#xA;   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.&lt;&gt;c__DisplayClass10.&lt;GetExecutor&gt;b__9(Object instance, Object[] methodParameters)&#xD;&#xA;   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Web.Http.Controllers.ApiControllerActionInvoker.&lt;InvokeActionAsyncCore&gt;d__0.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Web.Http.Controllers.ActionFilterResult.&lt;ExecuteAsync&gt;d__2.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Web.Http.Controllers.ExceptionFilterResult.&lt;ExecuteAsync&gt;d__0.MoveNext()" />
	</issue>
</OperationOutcome>`

**Comment by CorinaCiocanea** [comment]
Hello, I think this is solved now. Do you have an example with which you were able to reproduce it?

**Comment by mbaltus** [comment]
Thank you, this issue has been solved, but I'll raise a separate issue for the response codes.
