### ISSUE TITLE
Invalid URIs as identifier.system

### ISSUE THREAD

**Issue by michelemottini** [furore-fhir/spark#70]
http://spark.furore.com/fhir/Patient/spark1186 has an identifier.system `TTU` - that is not a valid URI.

...it could be a validation problem when creating  or updating the resource or a rendering problem...

**Comment by brianpos** [comment]
Data issue, so likely validation.

**Comment by mbaltus** [comment]
Although I agree you would like/expect an absolute URI here, why is it invalid? URIs can be relative according to the spec.

**Comment by michelemottini** [comment]
You're right, I was not thinking about relative URLs. 

So something like `TTU` should be interpreted as `<FHIR end-point>/TTU`, correct?

**Comment by mbaltus** [comment]
Yes, that's how I read it.
