### ISSUE TITLE
Where is the Reference DB

### ISSUE THREAD

**Issue by IDispose** [furore-fhir/spark#73]
I am not sure if I am missing something. Where do I find the mongodb database that backs the reference implementation? Am I expected to create my own? 

TIA

**Comment by tylrmac** [comment]
It took me awhile to figure this one out but you do have to create your own. 

The simplest method is to install Mongo and run mongod.exe (it's not automatically installed in your PATH so you'll have to find it at C:\Program Files\Mongo\...). Then when running Spark, navigate to <sparkaddress>/Maintenance/Initialize. That'll fill the database with example data.

Hope that helps!
