### ISSUE TITLE
How do you implement non-mongodb data store?

### ISSUE THREAD

**Issue by IDispose** [furore-fhir/spark#74]
Please feel free to correct if my comprehension is incorrect. 

The mongodb store allows spark to simply respond to queries with FHIR json formatted responses. This assumes that the data stored in the db is already formatted per FHIR specs. However, if I have, say an RDBMS that stored the data, I have to build a FhirStore (basically implement IFhirStore and create the json responses (of course using the Fhir .net API). Is that the recommended approach?

**Comment by mharthoorn** [comment]
Currently the FhirService connects to a IFhirStore. And the default implementation is MongoFhirStore. The way the service communicates to the FhirStore is with POCO's. So the FhirService deals with Request/Response. The store just deals with Fhir POCO classes from the fhir api. 

Currently to replace Mongo, you have to reimplement the IFhirStore, IGenerator and and ISnapshotStore. If you also wish to have search on a RDBMS too, you will need a replacement for that too. We are currently working on making that part simpler.
