### ISSUE TITLE
Returning only body of Binary resource doesn't work

### ISSUE THREAD

**Issue by mbaltus** [furore-fhir/spark#76]
According to the spec:

> when a read request is made for the binary resource that doesn't explicitly specify the FHIR content types "application/xml+fhir" or "application/json+fhir", then the content should be returned using the content type stated in the resource. e.g. if the content type in the resource is "application/pdf", then the content should be returned as a PDF directly.

Spark returns the Binary resource, even when the request is specifically for the content only.
Example: GET http://spark.furore.com/fhir/Binary/spark27 with an Accept header of text/plain will still return the complete Binary resource.

**Comment by ewoutkramer** [comment]
The documentation on this was unclear. We have discussed this during a FHIR-I meeting, see the final resolution here: http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=9258&start=0

**Comment by mbaltus** [comment]
Spark now returns the right format when you specifically ask for it, but should return that format by default. The response should only return a Binary resource when specifically asked for.
