### ISSUE TITLE
Prefer HTTP Header appears to cause Spark failure

### ISSUE THREAD

**Issue by ArnieTeres** [furore-fhir/spark#77]
Please evaluate whether this is a bug or something I am doing wrong.

The message in this file posts to the dstu2_master version of Spark without error
[good2_Request.txt](https://github.com/furore-fhir/spark/files/186754/good2_Request.txt)

The message in this file, generated through the FHIR client API contains a Prefer header and causes a null object reference error in Spark
[bad2_Request.txt](https://github.com/furore-fhir/spark/files/186757/bad2_Request.txt)

The message body in both messages is essentially identical. When I include the Prefer header in the good message it too fails with the same error.

The stack dump returned from Spark is:

{"Message":"An error has occurred.","ExceptionMessage":"Object reference not set to an instance of an object.","ExceptionType":"System.NullReferenceException","StackTrace":"   at Spark.Engine.Extensions.HttpRequestFhirExtensions.AcquireHeaders(HttpResponseMessage response, FhirResponse fhirResponse) in D:\\SPARK_FHIR_Server\\spark-dstu2-master\\spark-dstu2-master\\src\\Spark.Engine\\Extensions\\HttpRequestFhirExtensions.cs:line 96\r\n   at Spark.Engine.Extensions.HttpRequestFhirExtensions.CreateResponse(HttpRequestMessage request, FhirResponse fhir) in D:\\SPARK_FHIR_Server\\spark-dstu2-master\\spark-dstu2-master\\src\\Spark.Engine\\Extensions\\HttpRequestFhirExtensions.cs:line 124\r\n   at Spark.Core.FhirResponseHandler.<>c__DisplayClass0_0.<SendAsync>b__0(Task`1 task) in D:\\SPARK_FHIR_Server\\spark-dstu2-master\\spark-dstu2-master\\src\\Spark.Engine\\Filters\\FhirResponseHandler.cs:line 23\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Spark.Handlers.FhirMediaTypeHandler.<SendAsync>d__2.MoveNext() in D:\\SPARK_FHIR_Server\\spark-dstu2-master\\spark-dstu2-master\\src\\Spark.Engine\\Handlers\\MediaTypeHandler.cs:line 73\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()"}

**Comment by mbaltus** [comment]
It's not the header that causes a problem. I've tested creating a Patient with my .Net client, which does send the Prefer, and it works perfectly.
When I try to send the Patient from your examples, I do get an error from Spark with an OperationOutcome that tells me: "diagnostics=FormatException: The string '02/14/1998' is not a valid AllXsd value."
All dates should be represented as "yyyy-mm-dd", so please update that in your Patient resource. Spark should accept the resource after that. If not, please list the steps you've taken in a comment, so I can try and reproduce.

**Comment by ArnieTeres** [comment]
I updated the date format and received the same error stack dump. In my environment it is definitely the Prefer header causing the problem although I have no idea why. Including the Prefer causes the failure and excluding it fails regardless of the date format. I have never received any error on the date format (?)

Here is the portion of the FHIR API that I modify to eliminate the Prefer header:
File: fhir-net-api-master\fhir-net-api-master\src\Hl7.Fhir.Core\Rest\EntryToHttpExtensions.cs

            if (interaction.Method == Bundle.HTTPVerb.POST || interaction.Method == Bundle.HTTPVerb.PUT)
            {
                //request.Headers["Prefer"] = bodyPreference == Prefer.ReturnMinimal ? "return=minimal" : "return=representation";
            }

Here is the source I use to create the Patient resource:

            SerializationConfig.AcceptUnknownMembers = true;
            FhirClient client = new FhirClient(fhirUrl);
            client.PreferredFormat = ResourceFormat.Json;
            client.UseFormatParam = false;
            client.ReturnFullResource = true;

            var patient = new Patient();

            patient.Name = new List<HumanName>();
            patient.Name.Add(HumanName.ForFamily("Siemens").WithGiven("Test2"));

            patient.Gender = AdministrativeGender.Other;

            patient.BirthDate = "1998-02-14";

            Uri uri = new Uri("http://siemens.health.us");
            string url = uri.ToString();
            CodeableConcept idType = new CodeableConcept { Text = "MRN" };
            Identifier id = new Identifier { System = url, Value = "129712", Use = Identifier.IdentifierUse.Usual, Type = idType };
            patient.Identifier = new List<Identifier>();
            patient.Identifier.Add(id);

            patient.Telecom = new List<ContactPoint>();
            patient.Telecom.Add(new ContactPoint()
            {
                Value = "111-222-3456",
                System = ContactPoint.ContactPointSystem.Phone,
                Use = ContactPoint.ContactPointUse.Home
            });

            var entry = client.Create<Patient>(patient);

I am running the dstu2_master of Spark and the master of the FHIR API at github.com/ewoutkramer/fhir-net-api

**Comment by ArnieTeres** [comment]
Interesting development - The code above will work correctly with and without the Prefer header against the public Spark server at http://spark.furore.com/fhir but the Prefer header is definitely causing my in-house Spark to have trouble. Are there known issues when running Spark under iisexpress?

**Comment by brianpos** [comment]
My server (which was hard on spark long ago except based on sqlserver) runs fine in iisexpress.

**Comment by brianpos** [comment]
Feel free to test against http://sqlonfhir-dstu2.azurewebsites.net/fhir to see if works there too. It is running against one of the feature streams of the dot net client - with fhir path in it.

**Comment by ewoutkramer** [comment]
I remember there was a bug in the version of spark in November with the then current .NET API. But both have been fixed since then.  Is this still a problem in Spark?

**Comment by mbaltus** [comment]
The version in dstu2/master has been updated, so you could be running an older version where there is a bug with Prefer. Could you download Spark again and try if you've still got the problem?

**Comment by ArnieTeres** [comment]
Thank you for the suggestion.

I downloaded the latest version and I no longer have a problem with the Prefer header.

_____________________________________________________
SIEMENS           Medical Solutions - Health Services
Arnold Teres Architect
syngo Development
Siemens Medical Solutions USA, Inc.
40 Liberty Boulevard
Mail Code: 65-3
Malvern, PA 19355-9998, USA
Phone:                                                   +01 (610) 448-6167
Mobile:                                                  +01 (610) 761-3334
mailto: arnold.teres@siemens.com <mailto:arnold.teres@siemens.com>
_______________________________________________________
