### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by Matt2012** [furore-fhir/spark#78]
Apologies if wrong place for this but having issue accessing spark.furore.com/fhir due to CORS (Reason: CORS header 'Access-Control-Allow-Origin' missing).

Im following this tutorial but with your API details  http://docs.smarthealthit.org/tutorials/javascript/

I came across this blog article talking about this issue but without a clear fix. 
http://fhirblog.com/2014/08/08/cors-in-fhir/

Are you able to give me a heads up how to fix this and maybe where to post these sorts of questions?

**Comment by ewoutkramer** [comment]
Hi Matt, yes this is the right place.  I think spark has CORS headers that allow simply "everything", so I was not aware we were missing yet another CORS header. We are relying heavily on the .NET framework for this to work, so we'll have to see whether we can make it add that header.  I am no longer part of the Spark team, so maybe one of them can comment here.

**Comment by PaulDeac** [comment]
Hi Matt. We do have CORS headers that allow everything, after some investigation we found another internal error which caused preflighted cross-server requests to fail. We took care of it, in the next release everything should work properly, please let us know if you will still encounter any problems.

**Comment by vadimnehta** [comment]
I'm affected by this as well - when is the next release planned?
