### ISSUE TITLE
Request for security contact

### ISSUE THREAD

**Issue by AndersAbel** [furore-fhir/spark#87]
I have found a security issue in this code that I want to report privately. Please contact me via e-mail for details.

**Comment by brianpos** [comment]
Is the issue in the spark code, or the fhir dot net client code?

**Comment by AndersAbel** [comment]
It's in the src\Spark.Engine directory of this repository. Does that mean that it's in the Spark code? I'm sorry if I'm a bit unclear, but I'm not familiar with this project at all. I found the issue by searching for code that matched a certain pattern as part of some research I'm doing.

**Comment by AndersAbel** [comment]
For anyone else looking into this. I've shared the details with @brianpos through e-mail.
