### ISSUE TITLE
Create returns Content-Location but not Location

### ISSUE THREAD

**Issue by cknaap** [furore-fhir/spark#88]
When I create a new resource, e.g. POST {{server}}/fhir/Patient, if this is successful I get the expected 201 response status.  I also see the Content-Location in the response header being set following the FHIR spec with the new resource id and version id. However I was expecting to see this information carried in Location rather than Content-Location, as described in the FHIR spec [here](https://www.hl7.org/fhir/http.html#create).

**Comment by cknaap** [comment]
Follow-up problems:
- Content-Location contains the base url on a PUT response, but not on a GET response.
- Location is set on a GET response, although it has no meaning on that (see [here](https://www.subbu.org/blog/2008/10/location-vs-content-location)).

**Comment by mbaltus** [comment]
First follow-up problem is fixed, the second still exists.
