### ISSUE TITLE
FHIR Messaging

### ISSUE THREAD

**Issue by tutukar** [furore-fhir/spark#90]
Is there a plan to implement messaging in Spark? 

https://www.hl7.org/fhir/messaging.html

**Comment by mbaltus** [comment]
Spark is a RESTful FHIR server, which means you can perform the REST interactions defined in the specs, including storing and subsequently retrieving Bundles of type message on the /Bundle endpoint.
Spark doesn't process messages. The messaging paradigm, where some action is expected after the message has been received, is different from the REST paradigm which is mainly used for CRUD interactions.
My question to you would be: what would you expect Spark to do when you send a FHIR message to it?

**Comment by tutukar** [comment]
Sorry, I was thinking the reverse, events from FHIR servers based on resource subscriptions. I agree with you about messages being inbound to the FHIR server and doesn't belong in the RESTful space. I was thinking, resource subscriptions,

https://www.hl7.org/fhir/subscription.html

**Comment by tutukar** [comment]
and this answers my question,
https://github.com/furore-fhir/spark/issues/64

Thanks!
