### ISSUE TITLE
Coucbase or other store?

### ISSUE THREAD

**Issue by aceptra** [furore-fhir/spark#91]
I see some history in comments about proposal to connect Spark to **Couchbase**  (@wilsondy ) or other backend. 

What is the current status of this and what would it take to change the storage to Couchbase? We are more familiar with Couchbase  @here.

Thank you!

**Comment by wilsondy** [comment]
The storage / search/ indexing bits are abstract enough that we have plugged in Couchbase implementations without touching the Spark code directly.  We are using Sync Gateway and bucket shadowing to carry FHIR resources to/from a Mobile App and also serve them up via Spark to a web portal.  We even share code between mobile and server (Xamarin).

**Comment by brianpos** [comment]
Are you using the dot net client in the xamarin client too?
There is a PCL version of it.

**Comment by aceptra** [comment]
We currently have a REST API that we're looking to move all or part to FIHR.

Right now it already uses Couchbase with the .NET client.

**Comment by wilsondy** [comment]
No, on Mobile we use Couchbase Lite for seamless synchronization.  Our web portal uses the official FHIR REST Endpoints provided by Spark.

Relevant Packages on Android (iOS similar)

<package id="Couchbase.Lite" version="1.2.1.1" targetFramework="MonoAndroid60" />
  <package id="Couchbase.Lite.Storage.SystemSQLite" version="1.2.1.1" targetFramework="MonoAndroid60" />
  <package id="Hl7.Fhir.DSTU2" version="0.90.5-alpha1" targetFramework="MonoAndroid50" />

**Comment by aceptra** [comment]
@wilsondy, your Spark bits that are talking to Couchbase (not mongodb), are those on GitHub somewhere?

**Comment by cknaap** [comment]
Good to read that MongoDB is sufficiently abstracted away. Still we'll be making the line between MongoDB specific parts and Spark generic parts cleaner in the near future.
