### ISSUE TITLE
SQL Server Integration

### ISSUE THREAD

**Issue by lumisoftusa** [furore-fhir/spark#94]
First of all great efforts, I really liked it.
Well we have EMR and other alot of apps running and for storage we are using SQL SERVER.
Right now we are porting EMR on FHIR standard so please guide me how i can confiure Spark server with SQL Server as Storage.

Thanks

**Comment by cknaap** [comment]
As Spark is now, you will have to do a lot of work to get it running on SQL Server. See the steps [here on the wiki](https://github.com/furore-fhir/spark/wiki/Fitting-Spark-in-my-environment#using-spark-directly-against-your-own-datastore). We're working on a more flexible approach.

**Comment by mharthoorn** [comment]
See also: #74
