### ISSUE TITLE
$Everything Does not work

### ISSUE THREAD

**Issue by lumisoftusa** [furore-fhir/spark#96]
$Everything Does not work

**Comment by cknaap** [comment]
Could you be more specific on the exact rest call you tried, and on which server address?

**Comment by mharthoorn** [comment]
The current live server (spark.furore.com) isn't updated yet. That could be what he means. We will do a deployment before the connectathon in Baltimore (september 2016)

**Comment by lumisoftusa** [comment]
Yes it is not working on live server and i have tried this at local and no luck at all, Might this is missing because no API method hit during debugging.

**Comment by CorinaCiocanea** [comment]
We did have a bug on this (see #86 ). Except from that it seems to work fine. So, I will close this for now, but if you still encounter issues please re-open it and add more details.
